export {
  DEFAULT_API_URL,
  DEVICE_EXEC_MAX_OUTPUT_BYTES,
  DEVICE_EXEC_TIMEOUT_MS,
  ENTIRE_FS_ROOT,
  FILESYSTEM_SERVER_KEY,
  FRAME,
  MAX_IMAGE_READ_BYTES,
  MAX_READ_BYTES,
  RECONNECT_MAX_MS,
  RECONNECT_MIN_MS,
  RECONNECT_SPREAD_MS,
} from "@gaia/shared/bridge-core/constants";
