name: Quality Checks

on:
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.15.1"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install lefthook
        run: npm install -g lefthook

      - name: Run lefthook checks
        run: |
          cd ..
          lefthook run pre-commit

      - name: Build
        env:
          NEXT_PUBLIC_API_BASE_URL: "http://fake-api-for-build.example.com"
        run: pnpm build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "backend/pyproject.toml"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: |
          uv venv
          echo "$PWD/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip sync pyproject.toml
          uv add ruff mypy types-redis types-requests types-pytz bandit pip-audit detect-secrets

      - name: Install lefthook
        run: npm install -g lefthook

      - name: Run lefthook checks
        run: |
          source .venv/bin/activate
          cd ..
          lefthook run pre-commit
